/**
 * Copies the compiled contract ABIs and bytecode from contracts/out into packages/chain, so the
 * TypeScript side builds without Foundry. Run after changing a contract: npm run contracts:build
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const artifact = (file: string, name: string) =>
  JSON.parse(readFileSync(join(root, "contracts/out", file, `${name}.json`), "utf8")) as {
    abi: unknown[];
    bytecode: { object: string };
  };

const jobs = artifact("ProofDeskJobs.sol", "ProofDeskJobs");
const usdc = artifact("MockUSDC.sol", "MockUSDC");
const anchor = artifact("LedgerAnchor.sol", "LedgerAnchor");
const out = `// Generated by scripts/gen-chain-abi.ts from contracts/out. Do not edit.
export const proofDeskJobsAbi = ${JSON.stringify(jobs.abi, null, 2)} as const;

export const proofDeskJobsBytecode = "${jobs.bytecode.object}" as const;

/** Test-only token (open mint, EIP-3009). Never deploy outside local chains. */
export const mockUsdcAbi = ${JSON.stringify(usdc.abi, null, 2)} as const;

export const mockUsdcBytecode = "${usdc.bytecode.object}" as const;

export const ledgerAnchorAbi = ${JSON.stringify(anchor.abi, null, 2)} as const;

export const ledgerAnchorBytecode = "${anchor.bytecode.object}" as const;
`;
writeFileSync(join(root, "packages/chain/src/abi.ts"), out);
console.log("wrote packages/chain/src/abi.ts");
